'use strict';
const $=id=>document.getElementById(id);
const SESSION=document.querySelector('meta[name="local-session"]').content;
const STORE='weiguang-library-v2',OLD='weiguang-text-character-v1';
const fields={name:60,work:120,summary:800,personality:1000,likes:600,boundaries:1000,relationship:600};
const depthKeys=['values','motivations','contradictions','emotionalRange','relationshipStyle','rhythm','wordChoice','humor','avoid'];
const DEFAULT={name:'初始角色',work:'原创角色',summary:'一个好奇、温和、有主见的文字伙伴。',personality:'自然简洁，有自己的判断，偶尔幽默，不刻意讨好。',likes:'科幻故事与生活中的细节。',boundaries:'不盲目附和，不编造共同经历，承认不知道。',relationship:'逐渐熟悉的朋友。'};
let state,mode='demo',configured=false,searchConfigured=false,busy=false,editing=null,branchFrom=null,storageError=false;
const trim=(s,n)=>typeof s==='string'?s.trim().slice(0,n):'';
const id=()=>crypto.randomUUID();
function href(s){try{const u=new URL(s);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}}
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function current(){return state.roles.find(r=>r.id===state.active);}
function tell(text){$('status').textContent=(storageError?'浏览器保存失败，请立即导出备份。\n':'')+text;}
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));storageError=false;return true;}catch{storageError=true;tell('');return false;}}
function normalizeProfile(p){
  if(!p||typeof p!=='object')throw Error('角色资料格式错误');
  const r={};for(const [k,n]of Object.entries(fields)){if(p[k]!==undefined&&(typeof p[k]!=='string'||p[k].length>n))throw Error('角色字段过长或格式错误');r[k]=trim(p[k],n);}
  if(!r.name||!r.personality||!r.likes||!r.boundaries)throw Error('角色必填字段为空');
  r.id=typeof p.id==='string'&&/^[\w-]{1,80}$/.test(p.id)?p.id:id();r.origin=['web','knowledge','edited','custom'].includes(p.origin)?p.origin:'custom';r.createdAt=trim(p.createdAt,50)||new Date().toISOString();
  r.sources=(Array.isArray(p.sources)?p.sources:[]).slice(0,6).map(s=>({id:trim(s.id,10),title:trim(s.title,200),url:href(s.url),excerpt:trim(s.excerpt,5500),kind:trim(s.kind,30),retrievedAt:trim(s.retrievedAt,50)})).filter(s=>s.id&&s.url);
  r.facts=(Array.isArray(p.facts)?p.facts:[]).slice(0,8).map(f=>({text:trim(f.text,400),sourceId:trim(f.sourceId,10),evidence:trim(f.evidence,100)})).filter(f=>f.text&&r.sources.some(s=>s.id===f.sourceId));
  r.style=(Array.isArray(p.style)?p.style:[]).slice(0,5).map(s=>({text:trim(s.text,400),sourceIds:(Array.isArray(s.sourceIds)?s.sourceIds:[]).filter(x=>r.sources.some(s=>s.id===x)).slice(0,3)})).filter(s=>s.text);
  r.examples=(Array.isArray(p.examples)?p.examples:[]).slice(0,3).map(e=>({user:trim(e.user,250),assistant:trim(e.assistant,500)})).filter(e=>e.user&&e.assistant);
  r.unknowns=(Array.isArray(p.unknowns)?p.unknowns:[]).slice(0,8).map(s=>trim(s,300)).filter(Boolean);
  if(p.query&&typeof p.query.name==='string')r.query={name:trim(p.query.name,60),work:trim(p.query.work,120),provider:['knowledge','tavily','wiki'].includes(p.query.provider)?p.query.provider:'wiki'};
  r.knowledge=(Array.isArray(p.knowledge)?p.knowledge:[]).slice(0,8).map(s=>trim(s,400)).filter(Boolean);
  if(r.origin==='knowledge'||r.query?.provider==='knowledge'){r.sources=[];r.facts=[];r.style=r.style.map(s=>({text:s.text,sourceIds:[]}));}
  if(p.messages!==undefined&&(!Array.isArray(p.messages)||p.messages.length>2000))throw Error('每个角色最多导入 2000 条记录');
  r.messages=(p.messages||[]).map(m=>{if(!m||!['user','assistant'].includes(m.role)||typeof m.content!=='string'||m.content.length>10000||typeof m.time!=='string'||!Number.isFinite(Date.parse(m.time)))throw Error('聊天记录格式不正确');return {role:m.role,content:m.content,name:trim(m.name,60),time:m.time,source:['deepseek','demo','intro'].includes(m.source)?m.source:'demo',failed:m.failed===true};});const result=CharacterLayers.attach({...r,layers:p.layers,depth:p.depth});delete result.depth;return result;
}
function normalizeState(data){
  if(data?.version===1&&data.persona&&Array.isArray(data.messages)){const r=normalizeProfile({...data.persona,messages:data.messages});return {version:2,active:r.id,roles:[r]};}
  if(data?.version!==2||!Array.isArray(data.roles)||!data.roles.length||data.roles.length>30)throw Error('备份格式不正确或超过 30 个角色');
  const roles=data.roles.map(normalizeProfile);if(new Set(roles.map(r=>r.id)).size!==roles.length)throw Error('角色编号重复');return {version:2,active:roles.some(r=>r.id===data.active)?data.active:roles[0].id,roles};
}
function load(){let warning='';try{const raw=localStorage.getItem(STORE)||localStorage.getItem(OLD);if(raw){state=normalizeState(JSON.parse(raw));save();}}catch{warning='未能读取旧资料。原存储未主动清除；请导入有效备份。';}if(!state){const r=normalizeProfile(DEFAULT);state={version:2,active:r.id,roles:[r]};}return warning;}
function lock(v){busy=v;document.querySelectorAll('button,input,textarea,select').forEach(e=>e.disabled=v);}
async function api(route,body){let response;try{response=await fetch('/api/'+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Local-Token':SESSION},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(route==='research'?175000:70000)});}catch{throw Error('本地服务断开或请求超时。请检查后台与网络，稍后手动重试。');}const data=await response.json();if(!response.ok)throw Error(data.error||'请求失败');return data;}
function showMode(){ $('modeBadge').textContent=mode==='live'?'DeepSeek · 真实模式':'演示模式';$('connectionDot').textContent=configured?'●':'○';$('modeNotice').textContent=mode==='live'?'真实角色对话 · 人设与最近对话交给 DeepSeek 处理。资料库用于模拟，不是模型训练；资料可能有误。':'演示模式 · 不调用模型，不能理解问题。请在“连接设置”保存 DeepSeek 密钥以启用真实对话。';}
function tab(which){$('chatPanel').hidden=which!=='chat';$('dossierPanel').hidden=which!=='dossier';$('chatTab').className=which==='chat'?'selected':'';$('dossierTab').className=which==='dossier'?'selected':'';}
function renderMessages(){const r=current(),list=$('messages');list.replaceChildren();if(!r.messages.length){const card=node('div',undefined,'card');card.append(node('h3','与 '+r.name+' 的第一句话'),node('p','可以聊聊今天的事，或者问一个你真正在意的问题。','muted'));list.append(card);}for(const m of r.messages){const e=node('div',undefined,'message '+m.role);e.append(node('div',(m.role==='user'?'你':m.name||r.name)+(m.source==='deepseek'?' · DeepSeek':m.source==='intro'?' · 系统提示':' · 演示／旧记录')+(m.failed?' · 未获得回复':'')+' · '+new Date(m.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),'meta'),node('div',m.content,'bubble'));list.append(e);}list.scrollTop=list.scrollHeight;}
function sourceList(target,sources){for(const s of sources){const e=node('div',undefined,'source'),a=node('a',s.id+' · '+s.title);a.href=href(s.url);a.target='_blank';a.rel='noopener noreferrer';e.append(a,node('small',s.kind+' · '+s.retrievedAt.slice(0,10)));const d=node('details');d.append(node('summary','查看收集到的节选'),node('div',s.excerpt,'excerpt'));e.append(d);target.append(e);}}
function renderDossier(){const r=current(),box=$('dossier');box.replaceChildren();box.append(node('h2',r.name+' · 角色档案'),node('p',r.origin==='knowledge'?'模型已有知识生成 · 未联网核实，没有检索来源，可能存在记忆错误。':r.origin==='web'?'联网整理 · 风格为模型推断，事实及出处仍需核对。':r.origin==='edited'?'自定义调整 · 下方原始研究资料不代表你的修改也经过来源验证。':'自定义角色 · 由你设定，无联网查证。','muted'));
  const l=r.layers;
  function section(title,pairs){const card=node('div',undefined,'card layer-card');card.append(node('h3',title));for(const [label,value]of pairs){if(value){card.append(node('strong',label),node('p',value));}}box.append(card);}
  section('① 身份事实 · 应用内不可直接修改',[['名字 / 作品',[l.identity.name,l.identity.work].filter(Boolean).join(' · ')],['背景',l.identity.summary]]);
  section('② 核心人格 · 不被互动设置覆盖',[['性格',l.core.personality],['偏好',l.core.likes],['原则',l.core.boundaries],['价值排序',l.core.values],['动机',l.core.motivations],['内在矛盾',l.core.contradictions],['情绪表达',l.core.emotionalRange],['关系变化',l.core.relationshipStyle]]);
  const speech=l.core.speech;section('语言习惯 · 描述与推断',[['节奏',speech.rhythm],['措辞',speech.wordChoice],['幽默条件',speech.humor],['避免失真',speech.avoid]]);
  if(speech.catchphrases.length){box.append(node('h3','口癖候选 · 不保证原作准确，不机械重复'));for(const c of speech.catchphrases)box.append(node('p',c.text+' — '+c.context));}
  if(l.core.quotes.length){box.append(node('h3','采集文本中的台词 · 需核对人物与版本'));for(const q of l.core.quotes)box.append(node('p','「'+q.text+'」 ['+q.sourceId+'] '+q.context));}
  if(l.core.scenarios.length){box.append(node('h3','情境反应 · 原创模拟，非原作台词'));for(const s of l.core.scenarios)section(s.situation,[['内在冲突',s.innerConflict],['选择与原因',s.approach],['原创示例',s.example]]);}else box.append(node('p','旧版档案尚无深度情境。可重新生成一份分层档案，旧角色与对话仍保留。','fine'));
  section('③ 互动调整 · 可以修改',[['与你的关系',l.flex.relationship],['称呼',l.flex.address],['虚构场景',l.flex.scene],['回复篇幅',({brief:'偏简短',natural:'自然变化',detailed:'偏详细'})[l.flex.length]],['主动程度',({low:'主要回应',normal:'自然互动',high:'适度主动'})[l.flex.initiative]]]);
  if(r.knowledge.length){box.append(node('h3','模型记忆的背景 · 未核实'));r.knowledge.forEach(s=>box.append(node('p',s)));}
  if(r.query?.provider==='knowledge'&&r.origin==='edited')box.append(node('p','原始档案来自模型已有知识，未联网核实。','muted'));
  if(r.facts.length){box.append(node('h3','有来源的资料 · 请核对'));for(const f of r.facts){const c=node('div',undefined,'card');c.append(node('p',f.text),node('p','证据 ['+f.sourceId+']：'+f.evidence,'fine'));box.append(c);}}
  if(r.style.length){box.append(node('h3','表达风格推断'));for(const s of r.style)box.append(node('p',s.text+(s.sourceIds.length?' ['+s.sourceIds.join(', ')+']':'（未核实推断）')));}
  if(r.examples.length){box.append(node('h3','原创表达示例 · 非原作台词'));for(const e of r.examples){const c=node('div',undefined,'card');c.append(node('p','你：'+e.user),node('p',r.name+'：'+e.assistant));box.append(c);}}
  if(r.unknowns.length){box.append(node('h3','资料缺口 / 不确定之处'));r.unknowns.forEach(s=>box.append(node('p',s)));}
  if(r.sources.length){box.append(node('h3','来源与采集节选'));sourceList(box,r.sources);}
  const actions=node('div',undefined,'actions');const branch=node('button','创建自定义分支 / 审校核心');branch.addEventListener('click',()=>openEditor(true,r));actions.append(branch);if(r.query){const b=node('button',r.query.provider==='knowledge'?'重新按模型知识生成（会产生用量）':'重新联网收集（会产生用量）');b.addEventListener('click',()=>runResearch(r.query,true));actions.append(b);}const del=node('button','删除此角色');del.addEventListener('click',()=>{if(busy)return;if(state.roles.length===1){tell('至少保留一个角色。');return;}if(!confirm('删除此角色及其对话？请先导出需要保留的备份。'))return;state.roles=state.roles.filter(x=>x.id!==r.id);state.active=state.roles[0].id;save();render();});actions.append(del);box.append(actions);
}
function render(){const r=current();$('roleName').textContent=r.name;$('initial').textContent=Array.from(r.name)[0];$('roleMeta').textContent=[r.work,r.origin==='knowledge'?'模型知识 · 未联网核实':r.origin==='web'?'联网生成':r.origin==='edited'?'自定义调整':'自定义角色'].filter(Boolean).join(' · ');$('roleCount').textContent=state.roles.length+'/30';$('library').replaceChildren();for(const role of state.roles){const b=node('button',undefined,'role-button'+(r.id===role.id?' active':''));b.append(node('strong',role.name),node('small',role.work||'原创 / 自定义'));b.addEventListener('click',()=>{if(busy)return;state.active=role.id;save();render();tab('chat');tell('已切换，使用此角色独立的聊天记录。');});$('library').append(b);}renderMessages();renderDossier();showMode();}
function openEditor(fresh=false,source=null){editing=fresh?null:current().id;branchFrom=source;const r=source|| (fresh?{...DEFAULT,name:'新角色',work:'',summary:''}:current());for(const k of Object.keys(fields)){$(k).value=r[k]||'';$(k).readOnly=!fresh&&k!=='relationship';}const core=r.layers?.core||{};for(const k of depthKeys){$('depth-'+k).value=core[k]||core.speech?.[k]||'';$('depth-'+k).readOnly=!fresh;}const flex=source?.layers.flex||(!fresh?current().layers.flex:{});for(const k of ['address','scene'])$(k).value=flex[k]||'';$('length').value=flex.length||'natural';$('initiative').value=flex.initiative||'normal';$('editorTitle').textContent=source?'创建自定义分支':fresh?'创建自定义角色':'调整互动方式';$('layerEditorHint').textContent=fresh?'在保存前确定身份与核心人格。保存后进入保护状态；以后仍可再建分支。':'身份与核心人格为只读。调整称呼、场景和关系，不会重写核心；模型仍可能偏离设定。';$('editorDialog').showModal();}

async function runResearch(query,force=false){if(busy)return;if(!configured){$('settingsDialog').showModal();$('connectionStatus').textContent='请先填写 DeepSeek 密钥，用于生成角色资料。';return;}if(query.provider==='tavily'&&!searchConfigured){$('settingsDialog').showModal();$('searchConnection').textContent='全网检索需要 Tavily 密钥。也可改用百科检索。';return;}
  const cached=state.roles.find(r=>r.layers?.core.scenarios.length>0&&['web','knowledge'].includes(r.origin)&&r.query?.name===query.name&&r.query?.work===query.work&&r.query?.provider===query.provider);if(cached&&!force){state.active=cached.id;save();render();tab('chat');$('researchStatus').textContent='已使用保存的角色档案，无新调用。需要更新可到资料库重新生成。';return;}
  if(state.roles.length>=30){$('researchStatus').textContent='已达 30 个角色，请先备份并删除不再需要的角色。';return;}
  lock(true);$('candidates').replaceChildren();$('researchStatus').textContent=query.provider==='knowledge'?'DeepSeek 正在根据已有知识生成角色……未联网检索，通常需要几十秒。':'正在联网搜集资料，并交给 DeepSeek 分析……通常需要几十秒。';
  try{const data=await api('research',query);if(data.status!=='ready'){$('researchStatus').textContent=data.reason+'\n'+(data.warnings||[]).join('\n');for(const c of data.candidates||[]){const b=node('button',c.name+' · '+c.work);b.addEventListener('click',()=>{$('queryName').value=c.name;$('queryWork').value=c.work;runResearch({...query,name:c.name,work:c.work});});$('candidates').append(b);}if(data.sources?.length){const d=node('details');d.append(node('summary','查看本次检索来源'));sourceList(d,data.sources);$('candidates').append(d);}return;}
    const r=normalizeProfile({...data.profile,messages:[]});state.roles.push(r);state.active=r.id;mode='live';save();render();tab('chat');$('researchStatus').textContent='已建立 '+r.name+' 的档案并切换。'+(query.provider==='knowledge'?'基于模型已有知识，未联网核实。':'')+(data.warnings?.length?'\n'+data.warnings.join('\n'):'')+'\n可在“角色资料库”查看依据，在“编辑角色”调整。';tell('新角色已就绪，旧角色及对话保留在左侧。');
  }catch(e){$('researchStatus').textContent='未切换角色：'+e.message;}finally{lock(false);}}
async function send(text){text=text.trim();if(!text||busy)return;const r=current();if(r.messages.length>1997){tell('此角色记录已达上限，请导出备份后清空。');return;}const live=mode==='live',message={role:'user',content:text.slice(0,4000),name:'你',time:new Date().toISOString(),source:live?'deepseek':'demo'};r.messages.push(message);$('text').value='';renderMessages();save();
  if(!live){r.messages.push({role:'assistant',name:r.name,time:new Date().toISOString(),source:'demo',content:'【演示回复】这里已保存“'+r.name+'”的设定，但还没有调用模型。请在连接设置中配置 DeepSeek，然后切换到真实模式。'});renderMessages();save();tell('演示模式未调用模型。');return;}
  lock(true);tell(r.name+' 正在回复……');try{const {messages,...persona}=r;const data=await api('chat',{persona,messages:messages.filter(m=>m.source==='deepseek'&&!m.failed).slice(-20).map(m=>({role:m.role,content:m.content}))});r.messages.push({role:'assistant',name:r.name,content:data.content,time:new Date().toISOString(),source:'deepseek'});save();renderMessages();tell('DeepSeek 已返回真实回复。'+(data.usage?' 本次输入 '+data.usage.prompt_tokens+' / 输出 '+data.usage.completion_tokens+' token。':'')+(data.truncated?' 回复达到长度上限，可要求继续。':''));}catch(e){message.failed=true;save();renderMessages();$('text').value=text;tell(e.message+'\n内容已放回输入框，可手动重试；未使用模板替代。');}finally{lock(false);$('text').focus();}}
$('settingsOpen').addEventListener('click',()=>$('settingsDialog').showModal());document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
async function setKey(route,key,el){if(busy)return;if(location.protocol==='file:'){el.textContent='请双击 start.cmd，并在 http://127.0.0.1:3210 使用。';return;}lock(true);try{const d=await api(route,{key});configured=d.configured;searchConfigured=d.searchConfigured;if(route==='key'){mode=configured?'live':'demo';$('apiKey').value='';}else $('searchKey').value='';el.textContent=key?'已保存在后台内存中，实际调用时验证有效性。':'已移除密钥。';showMode();}catch(e){el.textContent=e.message;}finally{lock(false);}}
$('keyForm').addEventListener('submit',e=>{e.preventDefault();setKey('key',$('apiKey').value.trim(),$('connectionStatus'));});$('searchKeyForm').addEventListener('submit',e=>{e.preventDefault();setKey('search-key',$('searchKey').value.trim(),$('searchConnection'));});$('disconnect').addEventListener('click',()=>setKey('key','',$('connectionStatus')));$('disconnectSearch').addEventListener('click',()=>setKey('search-key','',$('searchConnection')));
$('toggleMode').addEventListener('click',()=>{if(mode==='demo'&&!configured){$('settingsDialog').showModal();return;}mode=mode==='live'?'demo':'live';showMode();});
$('researchForm').addEventListener('submit',e=>{e.preventDefault();const query={name:$('queryName').value.trim(),work:$('queryWork').value.trim(),provider:$('provider').value};if(query.name)runResearch(query);});
$('editRole').addEventListener('click',()=>openEditor());$('customNew').addEventListener('click',()=>openEditor(true));
$('personaForm').addEventListener('submit',e=>{e.preventDefault();if(busy)return;const values={};for(const k of Object.keys(fields))values[k]=$(k).value.trim();if(['name','personality','likes','boundaries'].some(k=>!values[k])){tell('请填写完整核心字段。');return;}try{const old=state.roles.find(r=>r.id===editing);const flex={relationship:values.relationship,address:$('address').value.trim(),scene:$('scene').value.trim(),length:$('length').value,initiative:$('initiative').value};let r;if(old){r=normalizeProfile({...old,layers:{...old.layers,flex}});state.roles[state.roles.indexOf(old)]=r;}else{if(state.roles.length>=30)throw Error('最多保存 30 个角色');const depth={...(branchFrom?.layers.core||{}),speech:{...(branchFrom?.layers.core.speech||{})},quotes:[]};for(const k of depthKeys){if(['rhythm','wordChoice','humor','avoid'].includes(k))depth.speech[k]=$('depth-'+k).value.trim();else depth[k]=$('depth-'+k).value.trim();}r=normalizeProfile({...values,depth,origin:'custom',messages:[],layers:undefined});r=normalizeProfile({...r,layers:{...r.layers,flex}});state.roles.push(r);}state.active=r.id;save();render();$('editorDialog').close();tell(old?'互动设置已保存，身份和核心保持不变。':branchFrom?'自定义分支已创建；原角色与记录保留。':'角色已创建，核心设定已进入保护状态。');branchFrom=null;}catch(e){tell(e.message);}});

$('chatTab').addEventListener('click',()=>tab('chat'));$('dossierTab').addEventListener('click',()=>tab('dossier'));$('composer').addEventListener('submit',e=>{e.preventDefault();send($('text').value);});$('text').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&e.keyCode!==229){e.preventDefault();send($('text').value);}});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.prompt)));
$('clear').addEventListener('click',()=>{if(confirm('清空此角色对话？角色资料和其他角色的记录会保留。')){current().messages=[];save();renderMessages();}});
$('export').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download='百变虚拟角色-' +new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);tell('已请求下载备份，请查看浏览器下载列表。');});$('import').addEventListener('click',()=>$('file').click());$('file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>10000000)throw Error('备份不能超过 10 MB');const next=normalizeState(JSON.parse(await f.text()));if(!confirm('导入将替换整个角色库与聊天记录。继续吗？'))return;state=next;save();render();tell('备份已导入。');}catch(e){tell('导入失败：'+e.message);}finally{$('file').value='';}});
async function initialize(){const warning=load();render();tell(warning||'角色与记录仅保存在此浏览器，建议定期导出。');if(location.protocol==='file:'){$('connectionStatus').textContent='请通过 start.cmd 启动后访问 http://127.0.0.1:3210。';return;}try{const d=await api('status');if(d.version!==4)throw Error('旧后台仍在运行，请重启后台再刷新。');configured=d.configured;searchConfigured=d.searchConfigured;mode=configured?'live':'demo';$('connectionStatus').textContent=configured?'DeepSeek 密钥已配置。':'待填写 DeepSeek 密钥。';$('searchConnection').textContent=searchConfigured?'Tavily 密钥已配置。':'百科检索无需此密钥。';showMode();}catch(e){tell(e.message);}}
initialize();
